name: env-plot-covid19
channels:
  - conda-forge
dependencies:
  - voila
  - python=3.8
  - matplotlib-base>=2.2.2
  - ipympl
  - widgetsnbextension
  - pandas
  - transonic
  - pythran
  - gast=0.3.3
  - nodejs=14.9.0
